Assets/XLua/Src/Editor/Hotfix.cs
mdb写入冲突是由于调用HotfixInject时，先读取了mdb文件，但是未释放，在return之前释放掉即可解决此问题。
另：方便使用者打包起见，建议类似这种地方`#if HOTFIX_ENABLE`可改为`#if HOTFIX_ENABLE || !UNITY_EDITOR`
=> 修复HOTFIX_DEBUG_SYMBOL模式下的mdb文件写入冲突

Assets/XLua/Src/Editor/Hotfix.cs
生成代码导出代理类型的时候，处理了不定参数的情况，但是Hotfix的时候，却没有这个判断，导致代码注入失败。
=> 修复Hotfix的类包含带param参数的函数时，findHotfixDelegate找不到对应的代理的问题。

Assets/XLua/Src/Editor/Template/LuaEnumWrap.tpl.txt, Assets/XLua/Src/Editor/Template/TemplateCommon.lua.txt
编译Android平台的时候会报类似如下编译错误（Editor中可以正常编译）：
Assets/XLua/Gen/EnumWrap.cs(149,106): error CS0117: `UnityEngine.RuntimePlatform' does not contain a definition for `BB10Player'
测试环境：Unity 5.4.3f1
在代码生成模版里屏蔽掉Obsolute的字段
=> 过滤枚举的Obsolute字段

Assets/XLua/Src/Editor/Hotfix.cs, Assets/XLua/Src/Editor/Template/LuaDelegateBridge.tpl.txt, Assets/XLua/Src/Utils.cs
1.修复某些情况生成代理类的时候，参数名为空导致的编译失败
2.修复导入一个带有名为Item的自定义属性的类时报错的问题（this[]这种生成的Item属性有参数，靠这个区分）
=> 一些修复，详见commit message

Assets/XLua/Examples/09_GenericMethod/Foo.cs, Assets/XLua/Src/Utils.cs
修正：类似NGUITools.AddMissingComponent<T>(this GameObject) where T:Component导致代码生成编译不过的问题
=> 修正：带泛型的扩展方法导致生成编译报错的问题

Assets/XLua/Resources/perf/profiler.lua.txt
=> profiler.report 调用次数变量命名错误

build/make_android_lua53.sh, build/make_android_luajit.sh
允许用户通过ANDROID_NDK环境变量设置NDK路径，例如：
export ANDROID_NDK=/usr/local/android-ndk-r10e
./make_android_lua53.sh
=> 允许用户通过ANDROID_NDK环境变量设置NDK路径

Assets/XLua/Examples/ExampleGenConfig.cs
=> 修正：WWW.threadPriority在WebGL下不可用，加入导出黑名单

Assets/XLua/Src/ObjectTranslator.cs, Assets/XLua/Src/TypeExtensions.cs, Assets/XLua/Src/Utils.cs
Changes:
1. Add IsNestedPublic and IsPublic as extension methods of Type
2. Using MethodInfo.CreateDelegate instead Delegate.CreateDelegate for UWP
=> 修复几个在UWP下编译不过的问题

Assets/XLua/Src/Editor/Hotfix.cs
雄生哥你好,如果在Gen文件夹不存在的情况下,调用了HotfixInject会抛出这个异常.
=> [*]fix DirectoryNotFoundException

Assets/XLua/Src/LuaEnv.cs, Assets/XLua/Src/ObjectTranslatorPool.cs
同时对ObjectTranslatorPool的Add/Find/Remove方法在开启THREAD_SAFE之后进行加锁。
另外有个问题尚未确认，即：在做了这些修改之后在C#层不会因多线程出现什么问题，但是在长时间的多线程运行模式下Lua虚拟机内部会有几率出现数据错乱。疑似因为原版Lua的native没有实现线程安全（[参考1](http://www.cnblogs.com/ghost240/p/3526185.html)，[参考2](https://stackoverflow.com/questions/3010974/purpose-of-lua-lock-and-lua-unlock?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa)），也许需要结合pthread在编译一份native试试看。
=> 将LuaEnv中的luaLock修改为非静态成员，避免在多线程多LuaEnv种出现死锁

build/CMakeLists.txt
xcode 10已经不在支持32位macos平台架构，从CMakeFileLists.txt去除该平台
=> osx平台不再支持32bit版本构建

Assets/XLua/Examples/06_Coroutine/Coroutine_Runner.cs, Assets/XLua/Examples/06_Coroutine/Resources/coruntine_test.lua.txt, Assets/XLua/Examples/06_Coroutine/Resources/cs_coroutine.lua.txt
看似原先的IEnumeratorHolder是为了能被stop而存在的，用StartCoroutine返回的Coroutine也能stop，
用coroutine做返回值可以实现协程里等待启动的新协程，而IEnumeratorHolder不行
=> 06 Coroutine示例支持协程等待协程

Assets/XLua/Src/StaticLuaCallbacks.cs
当Dispose被调用时，由于先Remove了ObjectTranslator, 所以在lua_close的时候调用LuaGC时会抛出signal 11， 但是在android上由于mono 处理了signal并不会导致程序奔溃，但是当自己处理sig_handler的时候就会存在问题.
=> 当Dispose被调用时，由于先Remove了ObjectTranslator, 所以在lua_close的时候调用LuaGC时会抛出signal 11， 但是在android上由于mono 处理了signal并不会导致程序奔溃，但是当自己处理sig_handler的时候就会存在问题.

Assets/XLua/Src/Editor/Generator.cs, Assets/XLua/Src/Editor/Template/LuaEnumWrap.tpl.txt, Assets/XLua/Src/Editor/Template/LuaEnumWrapGCM.tpl.txt
We have a huge c# enum file in our project, which may hold 1M memory, and the enums seldom used in lua.
So we decide to blacklist all field of this enum, and modified source to support this feature.
=> - add BlackList feature for enums

Assets/XLua/Src/Editor/Hotfix.cs
在mac osx中File.Exist函数对相对路径不友好.
=> fix: more rubost XLuaHotfixInject path combination

Assets/XLua/Src/Editor/Generator.cs
执行XLua/Generate Code
如果反射得到一个未设置泛型类型的方法那么类型的FullName是null
会导致lua那边_CsFullTypeName方法里面local name = t.FullName:gsub("&", ""):gsub("%+", ".") 这一句代码报错
谢谢.
=> 这里有可能是通过反射得到未设置泛型的类型导致lua脚本报错生成代码失败

Assets/XLua/Src/Utils.cs
We added profiler code in StaticLuaCallbacks::ImportType function, but our code throws exception in some circumstances, when it happens, we saw xlua->generate command will print: "SetCSTable for "System.Type" error:", but no specific error displayed.
So it comes this PR.
=> fix error display when StaticLuaCallbacks::ImportType throws

Assets/XLua/Src/Utils.cs
we have three functions:
public bool IsHaveHero(UInt32 id, bool isIncludeTimeLimited)
{        }
public bool IsHaveHero(UInt32 id, RoleInfoOwnState state)
{    // the second parameter is an enum
}
public bool IsHaveHero(UInt32 heroId)
{        }
we configured this function as [DoNotGen].
when call the function role:IsHaveHero(xx, xxx), in MethodWrap::Call, the stack top is 4(which should be 3)
after further investigation, we found that after loadUpvalue, the stack grows wongly
=> * fix LazyReflectionCall with overloaded methods

build/make_ios_luajit.sh
Hi.
I updated ios/luajit build script for xcode 10.1
in my case, $XCODEVER is "10.1" and I got 2 errors
* `make_ios_luajit.sh: line 26: [: missing `]'`
* `lipo: can't open input file: libxluav7.a (No such file or directory)`
i updated if lines.
Regards.
=> update ios luajit build shell for xcode10.1

Assets/XLua/Src/DelegateBridge.cs, Assets/XLua/Src/LuaDLL.cs
Dear,
We had to adapt xLua to AppleTV(tvOS).
Added some Preprocessor definition.
Please check and merge it.
https://apps.apple.com/jp/app/id1471596310#?platform=appleTV
This game app was almost made by xLua.
Thanks.
=> feat: add UNITY_TVOS

Assets/XLua/Editor/ExampleConfig.cs
当类型是开放类型的时候，在得到该类型的泛型参数后会再次调用泛型参数的declaringType代入函数，导致无限递归。
fix #865
fix #639  
泛型参数加上判断，略过开放的类型参数
=> fix: (ExampleConfig.typeHasEditorRef) stackoverflow error

Assets/XLua/Src/Editor/Generator.cs, Assets/XLua/Src/Editor/Hotfix.cs
I noticed that [v2.1.15](https://github.com/Tencent/xLua/releases/tag/v2.1.15f1) adds pointer filtering. This patch is to filter pointers in the code generation phase and the DLL injection phase.
=> Filter the use of pointers that are not supported.

Assets/XLua/Src/ObjectCasters.cs
在lua侧调用FileStream.Read(byte[] buffer, int offset, int length)接口, 无法正常获取buffer读到的值，需要用RawObject对象将byte[]包裹一下，类似下面这种方式。
`
public class BytesRef : RawObject 
{
byte[] data;
public BytesRef(byte[] data)
{
this.data = data;
}
public BytesRef(int length)
{
data = new byte[length];
}
public object Target
{
get
{
return data;
}
}
public byte this[int index]
{
get
{
return data[index];
}
set
{
data[index] = value;
}
}
}
`
然后在lua里面可以这样调用, 记得将xxx.bytes改成你的文件路径。
`
local buffer = CS.BytesRef(1024)
local path = "xxx.bytes"
local fs = CS.System.IO.FileStream(path, CS.System.IO.FileMode.Open)
local num = fs:Read(buffer, 0, 1024)
if num > 0 then
print('num:' .. tostring(num))
print('buffer:' .. buffer.Target)
end
fs:Close()
`
如果不对xLua ObjectCaster.cs中getBytes函数增加对RawObject类型处理，调用Read时会报错。
=> Fix使用RawObject处理byte[]作为函数参数时，byte[]为null的问题

Assets/XLua/Src/Editor/Template/LuaWrapPusher.tpl.txt
#1030 引入的static变量需要在LuaEnv销毁重启后重新初始化
=> 修复重启LuaEnv遇到的崩溃问题

README_EN.md
The most significant is that "inplace" is not a word. There are others too.
=> Grammatical changes

Assets/XLua/Editor/XLuaUnityDefaultConfig.cs
在 Assets/XLua/Editor 目录下创建了适用于 Unity 的 xLua 默认配置. 它将在环境为 Unity 2022 或更高版本时, 屏蔽 Span<T> 和 ReadOnlySpan<T> 相关的所有成员的生成
=> fix: 修复在 Unity 2022 下生成代码报 Span 无法作泛型参数的问题

build/CMakeLists.txt
xLua升级lua5.4.6，出现编译报错：'system' is unavailable: not available on iOS。
相关代码：lua5.4.6源码中的loslib.c line: 134中对其进行了解释。
故，cmake编译时需要增加宏LUA_USE_IOS。
=> 修复lua5.4.6，构建iOS平台时出现报错（'system' is unavailable: not available on iOS）

.github/workflows/build.yml, .github/workflows/publish.yml
1. 部分github action被弃用了必须更新了
2. github action不再提供mac-11的虚拟机
=> Fix github build
